Mikheev.a/excel parse optimization
skbkontur/Excel.TemplateEngine pull request #9
Opened 2022-03-22 08:52 UTC by AntonMikheev666

2022-03-23 17:11 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/ExcelDocumentPrimitives/ITablePart.cs
> +        IReadOnlyList<IReadOnlyList<ICell>> Cells { get; }
почему решил поменять на `IReadOnlyList`?
Если уж хочется акцентировать что это материализованная коллекция, то тогда уж `IReadOnlyCollection` лучше подходит, т.к. доступ по индексу нигде не требуется
Ну и в целом кажется что это изменение никак не помогает в решении конкретной задачи, только размер диффа увеличило :). Такое можно отдельным ревью кидать, чтоб ревьюеру меньше мозг включать приходилось и смотреть либо только стилистические изменения, либо только функциональные

2022-03-23 20:33 UTC, aldobrynin requested changes

2022-03-23 20:33 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/TypeCheckingHelper.cs
> +        public static bool IsList(Type type)
а чем не подходит `IsIList`?

2022-03-23 20:33 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/ListParser.cs
> +            var parsedCount = 0;
неиспользуемая переменная, можно убрать

2022-03-23 20:33 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +        public LazyTableReader([NotNull] byte[] excelData)
тут в конструкторе инициализирются всякие ресурсы (`MemoryStream`, `SpreadsheetDocument`) и их по-хорошему надо уметь высвобождать, реализовав интерфейс `IDisposable`

2022-03-23 20:33 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +    internal class LazyClassParser
Не думал в сторону допилить обычный `ClassParser` чтоб он так же умел и это было единственным возможным поведением `ITemplateEngine.Parse`?
То что сейчас реализовано - это очень похожее на старое, но с небольшими изменениями, и теперь поддерживать парсинг экселя в библиотеке станет в два раза сложнее из-за всей копипасты в папке `LazyParse`

2022-03-24 07:15 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/TypeCheckingHelper.cs
> +        public static bool IsList(Type type)
Потому что массив реализует IList. Что вообще не очевидно.

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +        /// Generated function accepts new item in Dictionary<ExcelTemplatePath, object> format, where Kay is item property path and Value is object to set this property to.
Надо экранировать `Dictionary&lt;ExcelTemplatePath, object&gt;`, иначе не будет комментария

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +            var setItemProps = new List<Expression>(new Expression[] {initNewItem});
Имеет смысл указать начальный размер, хотя бы `relativeItemProps.Length`

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Указать размер

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +            Action<IList, object> addInvokeAction = (list, item) => addMethodInfo!.Invoke(list, new[] {item});
`addInvokeAction` не используется

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +            var getLenExpression = Expression.Property(Expression.Convert(valueToSetExpression, typeof(ICollection)), "Count");
Можно использовать `nameof(ICollection.Count)`

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Ну и тут ровно 2 элемента в списке. Можно или размер указать, или через `yield return` сделать

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +        public LazyTableReader([NotNull] byte[] excelData)
Если нам по факту нужен стрим, то давайте сделаем еще один метод, который принимает стрим. Тогда потребители не должны будут вычитать все данные в память, а, например, сделают `File.OpenRead`.

2022-03-24 07:18 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +            var firstSheetId = spreadsheetDocument.WorkbookPart.Workbook.GetFirstChild<Sheets>().Elements<Sheet>().ElementAt(0).Id.Value;
`First` вместо `ElementAt`?

2022-03-24 07:22 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/ListParser.cs
> +            var parsedCount = 0;
Спасибо.

2022-03-24 09:24 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +        public LazyTableReader([NotNull] byte[] excelData)
Done

2022-03-24 10:51 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +    internal class LazyClassParser
Изначально просто запихнул метод из этого класса в `ClassParser`, не трогая старый `Parse`. Объединять новый функционал со старым не стал, потому что реализовывал только то, что нужно нам, а старый может ещё парсить всякие чекбоксы, структуру которых нужно поизучать, чтобы правильно парсить.

2022-03-24 11:19 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +            var setItemProps = new List<Expression>(new Expression[] {initNewItem});
Можно, но думаю, нет особого смысла ставить начальный размер, потому что количество выражений может быть разное, так как в этот список попадает создание объекта для свойства класса. Это отдельное выражение и сколько их будет, нам не известно.

2022-03-24 11:23 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Тоже заранее не известно, сколько будет элементов.

2022-03-24 11:24 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
> +            Action<IList, object> addInvokeAction = (list, item) => addMethodInfo!.Invoke(list, new[] {item});
Спасибо

2022-03-24 11:37 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Размер указал

2022-03-24 11:42 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +            var firstSheetId = spreadsheetDocument.WorkbookPart.Workbook.GetFirstChild<Sheets>().Elements<Sheet>().ElementAt(0).Id.Value;
А вот нет.) Первый в перечислении элемент != первый элемент по индексу. Я тоже сначала `First` использовал и недоумевал, почему в данные не те.

2022-03-24 12:17 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Так нет цели угадать точное количество элементов. Цель - уменьшить количество лишних аллокаций памяти. Например, пустой список изначально вообще не выделяет память и содержит в себе пустой массив. А первое добавление создаст новый массив всего на 4 элемента. Потом 8, 16 и т.д. Поэтому есть смысл создавать с каким-то начальным размером.

2022-03-24 13:07 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/ExcelDocumentPrimitives/ITablePart.cs
> +        IReadOnlyList<IReadOnlyList<ICell>> Cells { get; }
Вспомнил: поменял, чтобы было явно видно, что это не перечисление, а фиксированный список, по которому можно проходить многократно.
Да, в моей ветке это, ни к селу, ни к городу, извиняюсь. Могу удалить из ветки, или переделать на `IReadOnlyCollection `.

2022-03-24 13:40 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Добавил, но думаю, что это экономия сравнима с погрешностью. Запущу ка бенчмарк ещё разок, проверить.)

2022-03-24 13:51 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Да, ничего не изменилось
![image](https://user-images.githubusercontent.com/28303735/159930945-b8e688d2-d31d-4867-a7ed-0cd45b6f672f.png)

2022-03-24 13:52 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
@aldobrynin , вот сравнительные показатели, кстати.)
![image](https://user-images.githubusercontent.com/28303735/159931150-adea20a8-df64-4430-8026-428985919e8e.png)

2022-03-24 14:49 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/TypeCheckingHelper.cs
> +        public static bool IsList(Type type)
не очень понимаю это ограничение и почему тут нельзя обрабатывать вообще любую реализацию `IEnumerable<T>`
Видимо это следствие того что сейчас получается примерно такой код внутри делегата сгенерированного `GenerateChildListItemAdder`:
```csharp
void Foo(object model, Dictionary<ExcelTemplatePath, object> item)
{
    model.SomeList ??= new List<TItem>();
    var newItem = new TItem();
    foreach (var prop in item) {
        // initialize property prop.Key.RawPath of newItem with prop.Value
    }
    model.SomeList.Add(newItem);
}
```
Если в нём не инициализировать свойство `model.SomeList`, а только конвертировать `Dictionary<ExcelTemplatePath, object>` в `TItem`, и коллекцию инициализировать в `LazyClassParser` уже когда `ListParser` вернул `IEnumerable<TItem>`,  то и код в `GenerateChildListItemAdder` будет попроще

2022-03-24 14:52 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +        public LazyTableReader([NotNull] byte[] excelData)
ещё `currentRowReader` остался

2022-03-24 16:37 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +    internal class LazyClassParser
Я понимаю что ты сделал как можно проще, но я не вижу как поддержка парсинга чекбоксов противоречит оптимизации парсинга больших коллекций. Если бы это были взаимоисключающие функциональности - вопросов нет, будет отдельный метод, отдельные реализации парсеров и т.д.

Окей, может реализовывать весь функционал будет неоправданно затратно для вас сейчас, но можно минимизировать стоимость поддержки кода в будущем: 
 - убрать дублирование (например, `TextValueParser` вполне может быть единым носителем знаний как парсить строки в примитивы, если его переиспользовать в `AtomicValueParser`)
 - выделить точки расширения, которые позволят потом допилить поддержку чекбоксов и дропдаунов (тут конечно придётся подумать как расточить `ITableParser` чтоб так можно было сделать, ну или какой-то другой вариант придумать)

2022-03-25 03:23 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
У тебя в бенчмарк включается чтение данных из файла. Это не очень хорошо, т.к. может добавлять какую-то константу ко времени выполнения теста. Лучше это вынести за пределы теста и проверять конкретный метод.

2022-03-25 03:32 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +            var targetBytes = File.ReadAllBytes("ihclmeWith5kList.xlsx");
Каждую итерацию теста загружается массив байтов с диска. Стоит это сделать один раз и вне теста.

2022-03-25 03:32 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +            using (var templateDocument = GetTemplate())
Каждый раз загружается с диска и создаётся шаблон. Можно сделать это 1 раз на итерацию и вне теста.

2022-03-25 03:32 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +                var lazyTableReader = new LazyTableReader(targetBytes);
`LazyTableReader` надо обернуть в using

2022-03-25 03:33 UTC, Backs commented on Benchmark/Benchmark.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Бенчмарк у тебя только под core 3.1, а у нас .net 4.7.2. Стоит и для него проверить. Результаты могут отличаться разительно.

2022-03-25 03:39 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +            using (var templateDocument = GetTemplate())
https://benchmarkdotnet.org/articles/features/setup-and-cleanup.html

2022-03-25 03:42 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +    [MemoryDiagnoser]
Вот тут через RuntimeMoniker можно указать несколько фреймворков https://benchmarkdotnet.org/articles/features/baselines.html#sample-introjobbaseline

2022-03-25 06:33 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/TypeCheckingHelper.cs
> +        public static bool IsList(Type type)
Кстати, да: `ListParser` будет возвращать коллекцию `TItem`, а модель вместо добавления элементов можно сразу сеттить полученную коллекцию.

2022-03-25 06:52 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/ExcelDocumentPrimitives/ITablePart.cs
> +        IReadOnlyList<IReadOnlyList<ICell>> Cells { get; }
Кстати: недавно в MEDI мы тоже похоливарили на подобном месте и Серёжа нашёл описание такого подхода, где рекомендуют возвращать наиболее точный интерфейс, а принимать наиболее общий необходимый. Это тоже повлияло на применение именно `IReadOnlyList`.

"Return the most specific type, accept the most generic type": https://stackoverflow.com/questions/3434367/is-it-better-to-return-the-most-specific-or-most-general-type-from-an-action-met, https://enterprisecraftsmanship.com/posts/return-the-most-specific-type/

2022-03-25 06:53 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +        public LazyTableReader([NotNull] byte[] excelData)
Спасибо

2022-03-25 08:05 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +    internal class LazyClassParser
Общие мысли.
Сейчас `ClassParser` построен вокруг сложной базы нашего кода, который построен вокруг формата `xlsx`. причём кажется, что какая-от его часть не используется, по типу тех же чекбоксов, дропдаунов и части стилей. Разбираться в этом сейчас не хочется, а просто подменить старые классы ячеек на новые не получит, на первый взгляд.

Про минимизацию затрат на поддержку.
- Да, переиспользовать `TextValueParser` нужно, сделаю.
- Не особо понимаю, как я могу выделить их кодом. Чтобы допилить поддержку парса других элементов нужно либо писать другие ридеры, на подобии `LazyTableReader`, либо переделывать существующие ридеры, например, чтобы они возвращал объект и его тип по адресу ячейки. Но я не уверен, что в Excel всё есть ячейка, это нужно проработать. Думаю, не стоит писать код под функционал, который возможно не будет реализован.

2022-03-25 08:53 UTC, aldobrynin commented on Benchmark/Benchmark.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
net core 3.1 уже 2 года как out of support, предлагаю под net6 гонять бенчмарки (ну и net472, раз вам ещё актуально)

2022-03-25 09:01 UTC, aldobrynin commented on Benchmark/ParseVsLazyParse.cs
> +            var targetBytes = File.ReadAllBytes("ihclmeWith5kList.xlsx");
я бы тут предложил воспользоваться параметризацией и оставить два теста: `Parse` и `LazyParse`
А 500, 5000 и 10000 вынес в параметры https://benchmarkdotnet.org/articles/features/parameterization.html

2022-03-25 09:15 UTC, Backs commented on Benchmark/ParseVsLazyParse.cs
> +            var targetBytes = File.ReadAllBytes("ihclmeWith5kList.xlsx");
Для этого надо научиться генерить эксельки с нужным количеством строк. Сейчас они константны.

2022-03-25 09:15 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyTableReader.cs
> +            var firstSheetId = spreadsheetDocument.WorkbookPart.Workbook.GetFirstChild<Sheets>().Elements<Sheet>().ElementAt(0).Id.Value;
Ёпта

2022-03-25 11:43 UTC, aldobrynin commented on Benchmark/ParseVsLazyParse.cs
> +            var targetBytes = File.ReadAllBytes("ihclmeWith5kList.xlsx");
что мешает брать заранее подготовленные файлики `File.ReadAllBytes($"ihclmeWith{N}List.xlsx")`?

2022-03-29 07:22 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Нашёл косяк в бенчмарках: список не парсился, оттого и такая огромная разница.
Поправил модельку и запустил бенчмарк на коде без каких-либо оговоренных изменений.
![image](https://user-images.githubusercontent.com/28303735/160556345-59d0f754-0153-48cc-9c79-0572c9f7862c.png)

2022-04-01 13:50 UTC, AntonMikheev666 commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectPropertySettersExtractor.cs
>              var statements = new List<Expression>();
Исправленные бенчмарки показали, что старый и новый парс практически не отличаются по используемой памяти. Но показатели GC по разным поколениям заставляет задуматься, как долго память будет недоступна. Хочу посмотреть, как настроить более подробный отчёт по использованию памяти.
![image](https://user-images.githubusercontent.com/28303735/161276909-eb993ca4-cddf-4188-83b5-b0b809896e34.png)

2022-04-04 15:09 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ChildSetterGenerator.cs
>              var block = Expression.Block(new ParameterExpression[0], statements);
у `Expression.Block` есть перегрузка без параметров
```suggestion
            var block = Expression.Block(statements);
```

2022-04-04 15:13 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ChildSetterGenerator.cs
> +                        throw new ObjectPropertyExtractionException("Only array and list is supported as iterated collections");
```suggestion
                        throw new ObjectPropertyExtractionException("Only array and list are supported as iterated collections");
```

2022-04-04 15:14 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectChildSetterFabric.cs
> +    internal static class ObjectChildSetterFabric
`Fabric` это что-то ближе к ткани/материалу, ты наверно имел в виду `Factory`

2022-04-04 15:21 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectChildSetterFabric.cs
> +            return list.Select(x => (T)x).ToArray();
можно просто
```suggestion
            return list.Cast<T>().ToArray();
```

2022-04-05 08:44 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectConversionGenerator.cs
> +            => dictToObjectCache.GetOrAdd(objectType, x => BuildDictToObject(objectProps, x));
тут в теории может закэшироваться неправильное поведение, если одна и та же моделька используется в двух шаблонах, но в первом шаблоне используются не все поля из модельки, а во втором - используются
тогда в кэше будет лямбда выставляющая только поля, используемые в первом шаблоне

2022-04-05 08:44 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +                logger.Warn($"Failed to parse value {cell.CellValue} from {cell.CellPosition.CellReference} with type='{leafModelType}'");
лучше структурированные логи писать https://vostok.gitbook.io/logging/concepts/syntax/passing-properties:
```suggestion
                logger.Warn("Failed to parse value {CellValue} from {CellReference} with type='{Type}'", new {CellValue = call.CellValue, CellReference = cell.CellPosition.CellReference, Type = leafModelType});
```

2022-04-05 08:44 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/ListParser.cs
> +                        logger.Warn($"Failed to parse value {cell.CellValue} from {cell.CellPosition.CellReference} with type='{propType}'");
и тут тоже структурированные логи

2022-04-05 09:16 UTC, Backs commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +                logger.Warn($"Failed to parse value {cell.CellValue} from {cell.CellPosition.CellReference} with type='{leafModelType}'");
Думаешь, придется искать по CellValue, CellReference?

2022-04-05 09:20 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/LazyParse/LazyClassParser.cs
> +                logger.Warn($"Failed to parse value {cell.CellValue} from {cell.CellPosition.CellReference} with type='{leafModelType}'");
скорее иногда хочется поискать все подобные записи, а по полному совпадению `messageTemplate` фильтровать в кибане как-то проще и быстрее, чем по каким-то паттернам

2022-04-05 14:07 UTC, aldobrynin commented on Excel.TemplateEngine/ObjectPrinting/Helpers/ObjectConversionGenerator.cs
> +            => dictToObjectCache.GetOrAdd(objectType, x => BuildDictToObject(objectProps, x));
@AntonMikheev666 в файле остался неиспользуемый `dictToObjectCache`

2022-04-06 07:30 UTC, aldobrynin approved these changes

2022-04-19 13:21 UTC, merged